"""Templates for generated projects."""

from __future__ import annotations

import json
import textwrap
from datetime import date

from .catalog import DEPENDENCIES
from .models import ProjectOptions


def _quoted(items: list[str]) -> str:
    return "\n".join(f'    "{item}",' for item in items)


def _uv_extra_flags(o: ProjectOptions) -> str:
    return " ".join(f"--extra {profile}" for profile in o.profiles)


def _optional_dependencies() -> str:
    return "\n".join(
        f"{profile} = [\n{_quoted(list(packages))}\n]"
        for profile, packages in DEPENDENCIES.profiles.items()
    )


def _pyproject(o: ProjectOptions) -> str:
    dependencies = [
        *DEPENDENCIES.core,
        *DEPENDENCIES.tracking[o.tracking],
    ]
    dev = [*DEPENDENCIES.groups["dev"], *DEPENDENCIES.data_versioning[o.data_versioning]]
    return f'''[build-system]
requires = ["hatchling>=1.27"]
build-backend = "hatchling.build"

[project]
name = "{o.project_name}"
version = "0.1.0"
description = {json.dumps(o.title)}
readme = "README.md"
requires-python = ">={o.python_version}"
dependencies = [
{_quoted(dependencies)}
]

[project.optional-dependencies]
{_optional_dependencies()}

[project.scripts]
experiment = "{o.package_name}.cli:main"

[dependency-groups]
dev = [
{_quoted(dev)}
]
notebooks = [
{_quoted(list(DEPENDENCIES.groups["notebooks"]))}
]

[tool.hatch.build.targets.wheel]
packages = ["src/{o.package_name}"]

[tool.ruff]
line-length = 100
target-version = "py{o.python_version.replace(".", "")}"

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "SIM"]
ignore = ["UP037"]

[tool.pytest.ini_options]
addopts = "-q --strict-markers"
testpaths = ["tests"]
'''


def _environment_yml(o: ProjectOptions) -> str:
    pip_packages = [
        *DEPENDENCIES.groups["dev"],
        *DEPENDENCIES.groups["notebooks"],
        *DEPENDENCIES.data_versioning[o.data_versioning],
    ]
    pip_lines = "\n".join(f"      - {json.dumps(package)}" for package in pip_packages)
    return f"""name: {o.project_name}
channels:
  - conda-forge
dependencies:
  - python={o.python_version}
  - pip
  - pip:
      # Editable install reads runtime dependencies from pyproject.toml.
      - "-e .[{",".join(o.profiles)}]"
{pip_lines}
"""


def _setup_guide(o: ProjectOptions) -> str:
    uv = f"""### uv

```bash
uv sync {_uv_extra_flags(o)} --group notebooks
uv run experiment --config configs/experiment.toml
uv run pytest
uv run ruff check .
uv run python -m ipykernel install --user --name {o.project_name}-uv \\
  --display-name "Python ({o.title} - uv)"
uv run jupyter lab
```"""
    conda = f"""### Conda

```bash
conda env create --file environment.yml
conda activate {o.project_name}
experiment --config configs/experiment.toml
pytest
ruff check .
python -m ipykernel install --user --name {o.project_name}-conda \\
  --display-name "Python ({o.title} - Conda)"
jupyter lab
```"""
    if o.environment_manager == "uv":
        return "Install [uv](https://docs.astral.sh/uv/) and run:\n\n" + uv
    if o.environment_manager == "conda":
        return "Install Conda or Miniforge and run:\n\n" + conda
    return (
        "Choose one isolated environment for each working session; do not activate Conda and "
        "`.venv` together. Both paths install the same project dependencies.\n\n"
        + uv
        + "\n\n"
        + conda
    )


def _readme(o: ProjectOptions) -> str:
    integration = []
    if o.tracking == "mlflow":
        mlflow_command = "uv run mlflow ui" if o.environment_manager == "uv" else "mlflow ui"
        integration.append(
            f"- MLflow records parameters, metrics, and run artifacts (`{mlflow_command}`)."
        )
    else:
        integration.append("- Runs are recorded locally under `artifacts/runs/` as portable JSON.")
    if o.data_versioning == "dvc":
        integration.append(
            "- DVC versions large data/models. Git tracks `.dvc/config`, `.dvcignore`, `*.dvc`, "
            "`dvc.yaml`, and `dvc.lock`; only DVC's local cache, temp state, and local config are "
            "ignored."
        )
    return f"""# {o.title}

Reproducible experiment project with **{", ".join(o.profiles)}** profiles, generated by AIML
Project Scaffolder.

## Start here

{_setup_guide(o)}

## Composable profiles

This project declares every profile as a standard Python optional dependency. The generated setup
commands install the selected profiles: `{", ".join(o.profiles)}`. You can change the combination
later without regenerating the project.

| Project type | Recommended profiles |
|---|---|
| Classical ML | `general` |
| Tabular ML | `general` + `tabular` |
| Image/deep learning | `deep-learning` |
| Deep learning with preprocessing/metrics | `general` + `deep-learning` |
| Basic OpenAI/LLM application | `genai` |
| GenAI with CSV/data analysis | `general` + `genai` |
| Hugging Face dataset/evaluation workflow | `general` + `genai` + `hf` |
| RAG with embeddings/clustering/evaluation | `general` + `genai` |

Examples:

```bash
uv sync --extra general
uv sync --extra general --extra deep-learning
uv sync --extra general --extra genai
uv sync --extra general --extra genai --extra hf
```

For Conda, update the `profiles` selection in `configs/experiment.toml`, change the editable extra
list in `environment.yml`, then run `conda env update --file environment.yml --prune`.

## Experiment loop

1. Register the source and license in `DATA_SOURCES.md`; never modify `data/raw/` in place.
2. Put reusable logic in `src/{o.package_name}/`, not only in notebooks.
3. Copy `configs/experiment.toml`, change one hypothesis at a time, and run it.
4. Compare the manifests in `artifacts/runs/` (or the configured tracker).
5. Add tests for transformations and leakage-sensitive feature logic before scaling a run.

{chr(10).join(integration)}

## Layout

```text
configs/                 versioned experiment parameters
data/{{raw,interim,processed}}  local data stages
notebooks/               exploration only
src/{o.package_name}/    tested package and experiment runner
tests/                   fast automated checks
artifacts/runs/           generated run manifests (Git-ignored)
models/                  generated model artifacts (Git-ignored)
reports/figures/         publication-ready figures
```

## Configuration and secrets

Commit configuration, but never credentials. Copy `.env.example` to `.env` for local secrets.
The starter reads TOML with Python's standard library and records the config plus environment
metadata with every run. Replace `objective()` in `experiment.py` with the smallest testable
implementation of your hypothesis.

## Reproducibility checklist

- Commit dependency specifications/locks, configuration, code, data metadata/checksums, and seed.
- Fit preprocessing only on training folds; use pipelines to prevent leakage.
- Keep a final untouched test set and report uncertainty, not only a best score.
- Record model/data/license constraints and validate on slices that matter to users.
- For GenAI, version prompts and evaluation sets and record provider/model identifiers.

## Author

{o.author}
"""


def _experiment(o: ProjectOptions) -> str:
    mlflow_import = "import mlflow\n\n" if o.tracking == "mlflow" else ""
    mlflow_start = textwrap.dedent(
        """
        mlflow.set_experiment(config.project.name)
        with mlflow.start_run(run_name=run_id):
            mlflow.log_params({"seed": config.experiment.seed, "profiles": config.project.profile})
            mlflow.log_metrics(metrics)
            mlflow.log_artifact(str(manifest_path))
        """
    ).strip()
    tracking = textwrap.indent(mlflow_start, "    ") if o.tracking == "mlflow" else ""
    return f'''"""A minimal reproducible run. Replace objective() with your hypothesis."""

from __future__ import annotations

import json
import platform
import random
import subprocess
from dataclasses import asdict
from datetime import UTC, datetime
from pathlib import Path

{mlflow_import}from .config import AppConfig


def _git_revision() -> str | None:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"], text=True, stderr=subprocess.DEVNULL
        ).strip()
    except (FileNotFoundError, subprocess.CalledProcessError):
        return None


def objective(seed: int) -> dict[str, float]:
    """Deterministic smoke objective; replace with real training or evaluation."""
    rng = random.Random(seed)
    return {{"example_score": rng.random()}}


def run(config: AppConfig) -> Path:
    started = datetime.now(UTC)
    run_id = started.strftime("%Y%m%dT%H%M%S%fZ")
    metrics = objective(config.experiment.seed)
    manifest = {{
        "run_id": run_id,
        "started_at": started.isoformat(),
        "git_revision": _git_revision(),
        "python": platform.python_version(),
        "config": asdict(config),
        "metrics": metrics,
    }}
    output_dir = Path(config.output.directory) / run_id
    output_dir.mkdir(parents=True, exist_ok=False)
    manifest_path = output_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\\n", encoding="utf-8")
{tracking}
    return manifest_path
'''


def _license(o: ProjectOptions) -> str:
    return f"""MIT License

Copyright (c) {date.today().year} {o.author}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""


def _gitignore(o: ProjectOptions) -> str:
    data_rules = """# Local data (without DVC)
data/raw/**
data/interim/**
data/processed/**
models/**
!data/raw/.gitkeep
!data/interim/.gitkeep
!data/processed/.gitkeep
!models/.gitkeep
"""
    if o.data_versioning == "dvc":
        data_rules = """# DVC-managed data is intentionally not ignored here.
# `dvc add` adds actual data paths while their *.dvc metadata remains tracked by Git.
"""

    return f"""# Python bytecode and native extensions
__pycache__/
*.py[cod]
*$py.class
*.so

# Virtual environments and secrets
.venv/
venv/
env/
ENV/
.env
.env.*
!.env.example

# Packaging and build output
build/
dist/
*.egg-info/
.eggs/

# Tests, coverage, linters, and type checkers
.pytest_cache/
.coverage
.coverage.*
htmlcov/
.tox/
.nox/
.ruff_cache/
.mypy_cache/
.pyright/
.hypothesis/

# Jupyter
.ipynb_checkpoints/

# Data and generated experiment artifacts
{data_rules}
artifacts/runs/**
reports/figures/**
!artifacts/runs/.gitkeep
!reports/figures/.gitkeep

# Experiment trackers and training output
mlruns/
wandb/
lightning_logs/
checkpoints/
events.out.tfevents.*

# DVC local state (track .dvc/config and *.dvc metadata files)
.dvc/cache/
.dvc/tmp/
.dvc/config.local

# Editors and operating systems
.idea/
.vscode/
*.swp
*.swo
*~
.DS_Store
Thumbs.db

# Logs and temporary files
*.log
*.tmp
.cache/
"""


def _precommit(o: ProjectOptions) -> str:
    prefix = "uv run " if o.environment_manager == "uv" else "python -m "
    return f"""repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: {prefix}ruff check --fix
        language: system
        types: [python]
      - id: ruff-format
        name: ruff format
        entry: {prefix}ruff format
        language: system
        types: [python]
"""


def _uv_ci_job(o: ProjectOptions, name: str) -> str:
    return f"""  {name}:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true
      - run: uv python install {o.python_version}
      - run: uv sync --locked {_uv_extra_flags(o)} --group notebooks
      - run: uv run ruff check .
      - run: uv run ruff format --check .
      - run: uv run pytest --cov={o.package_name} --cov-report=term-missing
"""


def _conda_ci_job(o: ProjectOptions, name: str) -> str:
    return f"""  {name}:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {{0}}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # v4
        with:
          activate-environment: {o.project_name}
          environment-file: environment.yml
      - run: ruff check .
      - run: ruff format --check .
      - run: pytest --cov={o.package_name} --cov-report=term-missing
"""


def _ci(o: ProjectOptions) -> str:
    header = "name: CI\n\non:\n  push:\n  pull_request:\n\njobs:\n"
    if o.environment_manager == "uv":
        return header + _uv_ci_job(o, "quality")
    if o.environment_manager == "conda":
        return header + _conda_ci_job(o, "quality")
    return header + _uv_ci_job(o, "uv-quality") + _conda_ci_job(o, "conda-quality")


def project_files(o: ProjectOptions) -> dict[str, str]:
    package = o.package_name
    files = {
        "pyproject.toml": _pyproject(o),
        ".python-version": f"{o.python_version}\n",
        ".gitignore": _gitignore(o),
        ".env.example": "# OPENAI_API_KEY=\n# MLFLOW_TRACKING_URI=http://localhost:5000\n",
        ".pre-commit-config.yaml": _precommit(o),
        "README.md": _readme(o),
        "LICENSE": _license(o),
        "DATA_SOURCES.md": """# Data sources\n\nFor every source, record its owner, retrieval date, URL/version, license, checksum,\nallowed uses, sensitive fields, and known limitations.\n\n| Dataset | Version/date | License | Location | SHA-256 | Notes |\n|---|---|---|---|---|---|\n| | | | | | |\n""",
        "configs/experiment.toml": f'''[project]\nname = {json.dumps(o.project_name)}\nprofile = "{",".join(o.profiles)}"\nenvironment_manager = "{o.environment_manager}"\n\n[experiment]\nseed = 42\n\n[data]\nraw = "data/raw"\nprocessed = "data/processed"\n\n[output]\ndirectory = "artifacts/runs"\n''',
        f"src/{package}/__init__.py": '"""Project package."""\n',
        f"src/{package}/config.py": '''"""Typed, validated experiment configuration."""\n\nfrom __future__ import annotations\n\nimport tomllib\nfrom dataclasses import dataclass\nfrom pathlib import Path\n\n\n@dataclass(frozen=True, slots=True)\nclass ProjectConfig:\n    name: str\n    profile: str\n    environment_manager: str\n\n\n@dataclass(frozen=True, slots=True)\nclass ExperimentConfig:\n    seed: int\n\n\n@dataclass(frozen=True, slots=True)\nclass DataConfig:\n    raw: str\n    processed: str\n\n\n@dataclass(frozen=True, slots=True)\nclass OutputConfig:\n    directory: str\n\n\n@dataclass(frozen=True, slots=True)\nclass AppConfig:\n    project: ProjectConfig\n    experiment: ExperimentConfig\n    data: DataConfig\n    output: OutputConfig\n\n    @classmethod\n    def load(cls, path: str | Path) -> "AppConfig":\n        with Path(path).open("rb") as stream:\n            raw = tomllib.load(stream)\n        try:\n            seed = int(raw["experiment"]["seed"])\n            if seed < 0:\n                raise ValueError("experiment.seed must be non-negative")\n            return cls(\n                project=ProjectConfig(**raw["project"]),\n                experiment=ExperimentConfig(seed=seed),\n                data=DataConfig(**raw["data"]),\n                output=OutputConfig(**raw["output"]),\n            )\n        except (KeyError, TypeError) as exc:\n            raise ValueError(f"Invalid experiment config: {exc}") from exc\n''',
        f"src/{package}/experiment.py": _experiment(o),
        f"src/{package}/cli.py": f'''"""Experiment command-line entry point."""\n\nimport argparse\n\nfrom .config import AppConfig\nfrom .experiment import run\n\n\ndef main() -> None:\n    parser = argparse.ArgumentParser(description="Run a reproducible {", ".join(o.profiles)} experiment")\n    parser.add_argument("--config", default="configs/experiment.toml")\n    args = parser.parse_args()\n    manifest = run(AppConfig.load(args.config))\n    print(f"Run complete: {{manifest}}")\n''',
        "tests/test_config.py": f'''from {package}.config import AppConfig\n\n\ndef test_default_config_loads() -> None:\n    config = AppConfig.load("configs/experiment.toml")\n    assert config.experiment.seed == 42\n    assert config.project.profile == "{",".join(o.profiles)}"\n''',
        "tests/test_experiment.py": f"""from dataclasses import replace\n\nfrom {package}.config import AppConfig, OutputConfig\nfrom {package}.experiment import run\n\n\ndef test_run_writes_manifest(tmp_path) -> None:\n    config = AppConfig.load("configs/experiment.toml")\n    config = replace(config, output=OutputConfig(directory=str(tmp_path)))\n    manifest = run(config)\n    assert manifest.is_file()\n    assert '"example_score"' in manifest.read_text()\n""",
        "notebooks/README.md": "# Notebooks\n\nUse numbered notebooks for exploration. Restart-and-run-all before sharing, keep outputs small, and move reusable code into `src/`.\n",
        "data/raw/.gitkeep": "",
        "data/interim/.gitkeep": "",
        "data/processed/.gitkeep": "",
        "models/.gitkeep": "",
        "artifacts/runs/.gitkeep": "",
        "reports/figures/.gitkeep": "",
    }
    if o.include_ci:
        files[".github/workflows/ci.yml"] = _ci(o)
    if o.environment_manager in {"conda", "both"}:
        files["environment.yml"] = _environment_yml(o)
    if o.data_versioning == "dvc":
        files[".dvcignore"] = (
            "# This file is tracked by Git and controls paths DVC should not scan.\n"
            "/.venv\n/artifacts/runs\n"
        )
        files["dvc.yaml"] = "# Define reproducible data and training stages here.\nstages: {}\n"
    return files
